### PR TITLE
added a max_sum_subarray program in Go

### PR DESCRIPTION
**Pull request by CHuante**
Here we "go" I hope this is where you wanted the file (the link you sent me went to a 404 issue).  Is this the type of program you wanted?

### CODE REVIEW

**Review by suyash2796 — CHANGES_REQUESTED** [review]
hi @CHuante -  I like this program!
Just few questions. What is the time complexity here? Isn't it O(N^2)? Can we solve this in O(N) using Kadane dynamic programming approach? We only want to return max sum.

This program displays the fantastic use of arrays in Go so we can keep this program also in different directory if you can create a 'Go" directory here https://github.com/suyash2796/CSCognisanse/tree/master/arrays and put this program there.

**Comment by CHuante** [comment]
Here we go!  Looking into Kadanes algorithm I had accidentally done a o(n^2) instead of a o(n).  How's this new iteration?

**Review by suyash2796 — APPROVED** [review]
looks good! @CHuante

**Comment by suyash2796** [comment]
Golang program added by contributer @CHuante looks perfect!

**Pull request merged**
